### ISSUE TITLE
Roadmap Planning 2

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#1037]
Estimation for:
- [x] ETL
- [x] Link to MDF
- [x] Globus File Transfer Integration
- [x] Workflow Editor Improvements
- [x] Project and Research Publishing
