### ISSUE TITLE
Crowd Curation

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#1119]
Note, moved time estimate to sub-issues. See below.
Ability for the system and users to rate and show popular published data

- [x] Commenting on published data
- [x] Link to owner e-mail, for people logged in. 
- [x] Is this useful data? (how to represent: checkbox? radio button? comment?) - favorite
- [x] Tracking statistics on published data to show most popular: number of unique views, number of downloads.
- [x] User profile (initially datasets on 'starred' list) - see more in comments

**Comment by Terry-Weymouth** [comment]
Glenn, I want to add "user profile" to this issue.

**Comment by Terry-Weymouth** [comment]
User profile: (backend) resources/users.js, db/model/user_profiles.js; and in DB: userprofiles. My initial model was very free-form: just a name-value pair list; for example - to implement starred-datasets: {..., starred-datasets: [of dataset id's], ...} - probably want some const values, somewhere for the profile 'keys'; maybe in db/model/user_profiles.js??

**Comment by Terry-Weymouth** [comment]
Done with first mockup. To present to Monday meeting. Spent 3 days building mockup.

**Comment by Terry-Weymouth** [comment]
From Monday Meeting. Additional (updates) changes: see issue #1166. That 'completes' final draft of frontend. Adding new issue for backend. Shortly. Two day and a half for additional updates.

**Comment by Terry-Weymouth** [comment]
Note removed estimate 13, as companion issues #1165, #1166, and #1168 are (now) holding the current estimates. That is 13 -> 3, 3, 5, respectively.
