### ISSUE TITLE
Clean up database split-out and monitor code: checklist.

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#1137]
General Comments

- [ ] Code needs to be run through the formatter
- [ ] There are unused imports that can be cleaned up (formatter in PyCharm may fix this)
- [ ] File naming is inconsistent (e.g. deleteDatabases.py vs clear_database_tables.py vs run-given-tests.sh; etc - camelCase vs underscore_case vs snake-case)
- [x] Filenames (as above) for new testsdb files
- [ ] files and code have been copied from other parts: e.g. loadtemplates.js; makeUsersForTests vs calling mcuser.py for each user; clear_database_tables.py
- [x] clear_database_tables.py - Rather than a hard coded list of tables could use table_list to get a list of tables 

Items for **mcservers**
- [x] u, d options both reference /etc/materialscommons/config.dev; have -u reference /etc/materialscommons/config.unit
- [x] check_nginx is always called, make it a part of ps_servers and show if it is running
- [x] u, d options use same MCDIR setting; change d MCDB_DIR to ~/devdb

Issues for **mcmon**
- [ ] Doesn't follow common coding conventions used in other servers: directories are not under src, main.js is not the main module, instead it is name of server (mcmon.js)
- [ ] Inconsistent file names (CamelCase vs underscore_case)
- [ ] PublicationWacher.js spelled incorrectly
- [ ] Switch to verbose flag rather than server type; since it's not clear what server type is used for
- [ ] variable and function names should all be camelCase, not underscore_case
- [ ] Variables are being created in global scope (eg line 151 file_converter.js)
- [ ] use yield for calls such as convert_office_doc_if_needed
