### ISSUE TITLE
Epic - Initial use of Globus for Materials Commons

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#1219]
In order to understand how to use Globus we need to set up a test server and test (personal) clients, write initial test code, write a Globus API test suite, test transfer from/to local client to/from local server, and push into code examples for what we actually want to do. 

To complete the effort for upload:
- [ ] backend service to initiate transfer and record pending transfer in database.
- [ ] monitor to track transfer state, and update state info in database record
- [ ] monitor to incorporate and transformation of files once successfully upload
- [ ] UI elements to start upload task via service
- [ ] UI elements to reports state of upload: In progress, Failed, Completed

**Comment by gtarcea** [comment]
Globus project notes: https://docs.google.com/document/d/18IRF4pzQH-GoC0BTBPS_s6zw3XDnQCV--sRMZQBgu20/edit?usp=sharing_eip&ts=5a68db67
